ci: set system resource limits for PHP lang tests (#3736)
* ci: set system resource limits for PHP lang tests

Recently we had a job fail with:

```
Spawning 87 workers...
Warning: stream_socket_accept(): Accept failed: Connection timed out in /usr/local/src/php/run-tests.php on line 1448
ERROR: Failed to accept connection from worker.
```

This is happening because the job doesn't have the right QOS for
resource requests to be respected, so it gets a burstable QOS. Sadly,
the default is a burstable QOS. So we specifically request resources
so that we'll be assigned a guaranteed QOS.

* ci: try enforce-static-cpus

We're not being auto-assigned the guaranteed QoS, try forcing.

* ci: tweak based on latest data now that QoS is enforced